### ISSUE TITLE
ERC20 Token non-custodial

### ISSUE THREAD

**Issue by cryptopoli** [VerusCoin/Verus-Desktop#44] opened 2020-06-03 18:58 UTC
VerusDeskWallet v0.6.5-3
Token eth /  link have the same pub address, correct!
Token link/eth cannot be sent, see Attache.

![chainlink_2020 06 01_15h00m13s_001_](https://user-images.githubusercontent.com/38912635/83676175-8ae5f000-a5da-11ea-9d12-5b886a66c77f.png)

![Token_2020 06 03_20h37m53s_003_](https://user-images.githubusercontent.com/38912635/83676246-a9e48200-a5da-11ea-9bce-733faf91209c.png)
![eth-balance_2020 06 03_20h49m13s_004_](https://user-images.githubusercontent.com/38912635/83676998-cf25c000-a5db-11ea-8151-30112ac1a87f.png)

ETH stuck in chain is not written well (etherscan.io ) 
Transaction ID (TXID): 0xdc4c88570c17343bf28d80ddffe1749c9111fb7676f1c93c77bc6e696d81bdec ((veruswallet))

ETH Transaction to Bitstamp, stopped, gas problem?
IDtx: 0xd606dcfa6060b99cebda5408582ba7b456aaf129275b0d64ec94ce445296570f

![ETH_IDTX_2020 06 03_20h28m11s_002_](https://user-images.githubusercontent.com/38912635/83676322-ca144100-a5da-11ea-916a-f1eb00cfe0e2.png)

Please release my tokens for transmission, thank you very much.

weansipa@gmail.com

**Comment by Oink70** [comment] 2020-06-03 20:04
Just transferred my Ethereum from address 1 on  a VM to address 2 on my physical machine.
It cannot send the entire amount, the last digit (max 9 sats) needs to be removed in order for the transaction to succeed, leaving 8e-9 ETH in my wallet.

**Comment by cryptopoli** [comment] 2020-06-03 21:00
Tested again you may see further errors in the input.
Test TX with link to Binance: aborted with known message, the fee can not preset. 
![test_send_link_2020 06 03_22h26m47s_006_](https://user-images.githubusercontent.com/38912635/83686813-2c753d80-a5eb-11ea-987d-72745fd4552c.png)
 
Test Tx ETH 0.009 Amount.
![Test Tx ETH_2020 06 03_22h37m12s_009_](https://user-images.githubusercontent.com/38912635/83687129-9ee61d80-a5eb-11ea-9ca6-908dac46a4e0.png)

Again aborted because of gas problem, but I have enough ETH in my deposit.
Meldung: Error Occured durind contract execution 
![Etherscan_2020 06 03_22h46m23s_010_](https://user-images.githubusercontent.com/38912635/83687591-45322300-a5ec-11ea-8b51-b4330d061a68.png)

**Comment by cryptopoli** [comment] 2020-06-04 07:11
2 Transactionen von Bitstamp wurden korrekt gesendet, In verusDeskWallet kein Eingang notiert?
![ETH_IN-OUT_2020 06 04_09h08m01s_001_](https://user-images.githubusercontent.com/38912635/83725953-185d2a80-a643-11ea-891f-9dc8dd6f5bf5.png)

Withdrawal
Jun. 03, 2020
09:48 PM UTC
Main Account

0.02000000 ETH
0.00100000 ETH
Transaction ID (TXID): 0x182a7c220f6e61631acd88ebe473de8c0f3131848b5e6728dfc4711f81120c36 ((veruswallet))
Withdrawal
Jun. 01, 2020
12:52 PM UTC
Main Account
0.00682720 ETH
0.00100000 ETH
Transaction ID (TXID): 0xdc4c88570c17343bf28d80ddffe1749c9111fb7676f1c93c77bc6e696d81bdec ((veruswallet))

**Comment by cryptopoli** [comment] 2020-06-04 07:22
Link IN/OUT all send attempts failed? No indications of incorrect input to be seen!
![Link IN_OUT_2020 06 04_09h12m47s_002_](https://user-images.githubusercontent.com/38912635/83726571-00d27180-a644-11ea-935c-dcd0b469d150.png)

I have now received all the information that I know of that there are problems with VerusDeskWallet deposits/withdrawals for which I am not responsible.

I am waiting for further inputs from Dev`s.

**Comment by cryptopoli** [comment] 2020-06-04 11:22
Have Verus Desk Wallet on a 2nd PCdesk newly set up with new SEED/address.
Test: 0.5 Link from 1st PcDesk sent to new address, unfortunately the same error message and abort appears!  
Please contact Miketouth and discuss the situation, thanks.

![link new adress_2020 06 04_13h12m12s_003_](https://user-images.githubusercontent.com/38912635/83750554-c11c8180-a665-11ea-8805-1d1b03cecff8.png)

**Comment by cryptopoli** [comment] 2020-06-04 12:33
> Just transferred my Ethereum from address 1 on a VM to address 2 on my physical machine.
> It cannot send the entire amount, the last digit (max 9 sats) needs to be removed in order for the transaction to succeed, leaving 8e-9 ETH in my wallet.

Yes, I know, that's why my ETH deposit is filled accordingly.
I have also tested with two vrsc-profiles on 2 machines, again no transaction is completed and the test is aborted immediately.
Please connect to Miketout to solve the problem.

**Comment by cryptopoli** [comment] 2020-06-06 06:41
Continued imprisonment for ERC20 ETH/ ChainLink Token.
Is there any progress to report on the matter?
![chainlink_2020 06 01_15h00m13s_001_](https://user-images.githubusercontent.com/38912635/83937919-014c4300-a7d1-11ea-8d77-47b93a8ab13e.png)

**Comment by cryptopoli** [comment] 2020-06-11 09:22
Update Verus 0.7.0 installed.
ETH can now deposit/pay out correctly in the Explorer.

Token ChainLink payout still blocks with known warning.
!![chainlink_2020 06 01_15h00m13s_001_](https://user-images.githubusercontent.com/38912635/84368091-6939c980-abd5-11ea-8db9-a2ef1ede35c2.png)

Is there any progress to report on the matter?

**Comment by cryptopoli** [comment] 2020-06-18 09:54
Verus Desktop v0.7.0-3
Chainlink still blocked, our efforts are not bearing fruit?
![error_link_2020 06 18_11h13m51s_001_](https://user-images.githubusercontent.com/38912635/85006389-5b96bd80-b15a-11ea-93ce-75746d725084.png)

Is there any progress to report on the matter?

**Comment by cryptopoli** [comment] 2020-06-23 10:29
Today:   Test transmission ETH
![ETH-send_2020 06 23_10h51m38s_001_](https://user-images.githubusercontent.com/38912635/85392507-e9541d80-b54b-11ea-8c65-af1467c7da9e.png)

a few minutes later Out message...
![ETH- Send_2020 06 23_12h16m02s_002_](https://user-images.githubusercontent.com/38912635/85392598-07ba1900-b54c-11ea-8e31-b57331402111.png)

Explorer reports cecancelet, fee charged (loss)
https://etherscan.io/tx/0x38219fe242d6de20c0f037c4ed0613c8a65b5aedd3b7776e21a3c286319396e6

Token Chainlink still blocked .
Is there any progress to report on the matter?

**Comment by cryptopoli** [comment] 2020-06-26 13:56
Even on 2nd PC with new profile Veruswallet v0.7.0-3 and current SEED, will erc20 Token Link/ETH remain blocked? A solution to this problem is urgently desired!

![verus-link blocket_Freitag, 26  Juni 2020_15h34m23s_001_](https://user-images.githubusercontent.com/38912635/85864948-7c4bbc80-b7c5-11ea-9b56-978be779e0b2.png)


Is there any progress to report on the matter?

**Comment by cryptopoli** [comment] 2020-07-01 21:59
Verus v0.7.0-4, Still Token link/eth payout blocked?
![linkethblocket_2020 07 01_23h53m28s_002_](https://user-images.githubusercontent.com/38912635/86295271-7e16e500-bbf6-11ea-8c59-564aa469fe7c.png)

Is there any progress to report on the matter?

**Comment by cryptopoli** [comment] 2020-07-06 18:56
"ERC20 token transmission failed"
Verus v0.7.0-4 In my case, so I hope I'm not the only one, I can deposit but not withdraw.

The link below lists the reasons why tokens are not paid out.
https://info.etherscan.com/reason-for-failed-transaction/

Hello to VerusDeskWallet users, ERC20 Token Link/ETH deposits and withdrawals are not executed correctly, messages about too little GAS do not reflect the fact that there are enough ETH credits. Has anyone had the same experience?  The support in case of discrepancies could not help so far. I report a technical program error?

Is there any progress to report on the matter?

**Comment by michaeltout** [comment] 2020-08-05 16:57
So far this problem has only been reported and reproduced for LINK (no other ERC20s) in a specific scenario, and it is being looked into. In the meantime, if you experience this problem with LINK, copy your ERC20 WIF key from the receive screen and use it to access your LINK wallet from another source.

**Comment by cryptopoli** [comment] 2020-08-05 22:16
In my "ChainLink" case, was moved to another account with Wkey, so my problem is solved.
Since there is no security regarding Link-ERC20 tokens yet, I will not use VerusWallet, thank you for your help.

**Comment by michaeltout** [comment] 2020-08-06 11:06
There is security, as all stored lite mode wallets (electrum & erc20) are securely password encrypted, but the LINK usability issue is under development. Thank you for the feedback and responsiveness so far. I'll keep this issue open until it is resolved, until then, if anyone experiences the same issue, feel free to add to this thread.

**Comment by michaeltout** [comment] 2021-05-09 14:30
This, should now be resolved in the latest version (0.7.3 and newer) due to a refactor of the ETH/ERC20 backend

**Closed by michaeltout** 2021-05-09 14:30 UTC
